application: shiftdiff
version: dev
runtime: python27
api_version: 1
threadsafe: true


handlers:
- url: /
  script: shiftdiff.app
- url: /static
  static_dir: static
- url: /.*
  login: required
  script: shiftdiff.app

libraries:
- name: jinja2
  version: latest
